import PropTypes, { Requireable, Validator } from 'prop-types';

import {
  Theme,
  Typography,
  Colors,
  Spacings,
  IconSizes,
  BorderRadius,
  BorderWidth,
  FontWeight,
  Breakpoints,
  MediaQueries,
  Grid,
  Transitions,
  ZIndex,
  Typeface,
  Elevation,
  States,
} from '../types';

const typePropType = PropTypes.shape({
    font: PropTypes.string.isRequired,
    fontWeight: PropTypes.string.isRequired,
    fontSize: PropTypes.string.isRequired,
    letterSpacing: PropTypes.string.isRequired,
    case: PropTypes.string.isRequired,
} as { [key in keyof Typography]: Requireable<string> }).isRequired;

const gridPropType = PropTypes.shape({
    priority: PropTypes.number.isRequired,
    breakpoint: PropTypes.oneOf([
        'default',
        'sm',
        'md',
        'lg',
        'xl',
        'xxl'
    ]).isRequired,
    cols: PropTypes.number.isRequired,
    maxWidth: PropTypes.string.isRequired,
    gutter: PropTypes.string.isRequired,
  }).isRequired;

export const themePropType = PropTypes.shape({
        colors: PropTypes.shape({
            transparent: PropTypes.string.isRequired,
            black: PropTypes.string.isRequired,
            white: PropTypes.string.isRequired,
            // Red
            red50: PropTypes.string.isRequired,
            red100: PropTypes.string.isRequired,
            red200: PropTypes.string.isRequired,
            red300: PropTypes.string.isRequired,
            red400: PropTypes.string.isRequired,
            red500: PropTypes.string.isRequired,
            red600: PropTypes.string.isRequired,
            red700: PropTypes.string.isRequired,
            red800: PropTypes.string.isRequired,
            red900: PropTypes.string.isRequired,
            // Pink
            pink50: PropTypes.string.isRequired,
            pink100: PropTypes.string.isRequired,
            pink200: PropTypes.string.isRequired,
            pink300: PropTypes.string.isRequired,
            pink400: PropTypes.string.isRequired,
            pink500: PropTypes.string.isRequired,
            pink600: PropTypes.string.isRequired,
            pink700: PropTypes.string.isRequired,
            pink800: PropTypes.string.isRequired,
            pink900: PropTypes.string.isRequired,
            // Purple
            purple50: PropTypes.string.isRequired,
            purple100: PropTypes.string.isRequired,
            purple200: PropTypes.string.isRequired,
            purple300: PropTypes.string.isRequired,
            purple400: PropTypes.string.isRequired,
            purple500: PropTypes.string.isRequired,
            purple600: PropTypes.string.isRequired,
            purple700: PropTypes.string.isRequired,
            purple800: PropTypes.string.isRequired,
            purple900: PropTypes.string.isRequired,
            // Deep Purple
            deepPurple50: PropTypes.string.isRequired,
            deepPurple100: PropTypes.string.isRequired,
            deepPurple200: PropTypes.string.isRequired,
            deepPurple300: PropTypes.string.isRequired,
            deepPurple400: PropTypes.string.isRequired,
            deepPurple500: PropTypes.string.isRequired,
            deepPurple600: PropTypes.string.isRequired,
            deepPurple700: PropTypes.string.isRequired,
            deepPurple800: PropTypes.string.isRequired,
            deepPurple900: PropTypes.string.isRequired,
            // Indigo
            indigo50: PropTypes.string.isRequired,
            indigo100: PropTypes.string.isRequired,
            indigo200: PropTypes.string.isRequired,
            indigo300: PropTypes.string.isRequired,
            indigo400: PropTypes.string.isRequired,
            indigo500: PropTypes.string.isRequired,
            indigo600: PropTypes.string.isRequired,
            indigo700: PropTypes.string.isRequired,
            indigo800: PropTypes.string.isRequired,
            indigo900: PropTypes.string.isRequired,
            // Blue
            blue50: PropTypes.string.isRequired,
            blue100: PropTypes.string.isRequired,
            blue200: PropTypes.string.isRequired,
            blue300: PropTypes.string.isRequired,
            blue400: PropTypes.string.isRequired,
            blue500: PropTypes.string.isRequired,
            blue600: PropTypes.string.isRequired,
            blue700: PropTypes.string.isRequired,
            blue800: PropTypes.string.isRequired,
            blue900: PropTypes.string.isRequired,
            // Light Blue
            lightBlue50: PropTypes.string.isRequired,
            lightBlue100: PropTypes.string.isRequired,
            lightBlue200: PropTypes.string.isRequired,
            lightBlue300: PropTypes.string.isRequired,
            lightBlue400: PropTypes.string.isRequired,
            lightBlue500: PropTypes.string.isRequired,
            lightBlue600: PropTypes.string.isRequired,
            lightBlue700: PropTypes.string.isRequired,
            lightBlue800: PropTypes.string.isRequired,
            lightBlue900: PropTypes.string.isRequired,
            // Cyan
            cyan50: PropTypes.string.isRequired,
            cyan100: PropTypes.string.isRequired,
            cyan200: PropTypes.string.isRequired,
            cyan300: PropTypes.string.isRequired,
            cyan400: PropTypes.string.isRequired,
            cyan500: PropTypes.string.isRequired,
            cyan600: PropTypes.string.isRequired,
            cyan700: PropTypes.string.isRequired,
            cyan800: PropTypes.string.isRequired,
            cyan900: PropTypes.string.isRequired,
            // Teal
            teal50: PropTypes.string.isRequired,
            teal100: PropTypes.string.isRequired,
            teal200: PropTypes.string.isRequired,
            teal300: PropTypes.string.isRequired,
            teal400: PropTypes.string.isRequired,
            teal500: PropTypes.string.isRequired,
            teal600: PropTypes.string.isRequired,
            teal700: PropTypes.string.isRequired,
            teal800: PropTypes.string.isRequired,
            teal900: PropTypes.string.isRequired,
            // Green
            green50: PropTypes.string.isRequired,
            green100: PropTypes.string.isRequired,
            green200: PropTypes.string.isRequired,
            green300: PropTypes.string.isRequired,
            green400: PropTypes.string.isRequired,
            green500: PropTypes.string.isRequired,
            green600: PropTypes.string.isRequired,
            green700: PropTypes.string.isRequired,
            green800: PropTypes.string.isRequired,
            green900: PropTypes.string.isRequired,
            // Light green
            lightGreen50: PropTypes.string.isRequired,
            lightGreen100: PropTypes.string.isRequired,
            lightGreen200: PropTypes.string.isRequired,
            lightGreen300: PropTypes.string.isRequired,
            lightGreen400: PropTypes.string.isRequired,
            lightGreen500: PropTypes.string.isRequired,
            lightGreen600: PropTypes.string.isRequired,
            lightGreen700: PropTypes.string.isRequired,
            lightGreen800: PropTypes.string.isRequired,
            lightGreen900: PropTypes.string.isRequired,
            // Lime
            lime50: PropTypes.string.isRequired,
            lime100: PropTypes.string.isRequired,
            lime200: PropTypes.string.isRequired,
            lime300: PropTypes.string.isRequired,
            lime400: PropTypes.string.isRequired,
            lime500: PropTypes.string.isRequired,
            lime600: PropTypes.string.isRequired,
            lime700: PropTypes.string.isRequired,
            lime800: PropTypes.string.isRequired,
            lime900: PropTypes.string.isRequired,
            // Yellow
            yellow50: PropTypes.string.isRequired,
            yellow100: PropTypes.string.isRequired,
            yellow200: PropTypes.string.isRequired,
            yellow300: PropTypes.string.isRequired,
            yellow400: PropTypes.string.isRequired,
            yellow500: PropTypes.string.isRequired,
            yellow600: PropTypes.string.isRequired,
            yellow700: PropTypes.string.isRequired,
            yellow800: PropTypes.string.isRequired,
            yellow900: PropTypes.string.isRequired,
            // Amber
            amber50: PropTypes.string.isRequired,
            amber100: PropTypes.string.isRequired,
            amber200: PropTypes.string.isRequired,
            amber300: PropTypes.string.isRequired,
            amber400: PropTypes.string.isRequired,
            amber500: PropTypes.string.isRequired,
            amber600: PropTypes.string.isRequired,
            amber700: PropTypes.string.isRequired,
            amber800: PropTypes.string.isRequired,
            amber900: PropTypes.string.isRequired,
            // Orange
            orange50: PropTypes.string.isRequired,
            orange100: PropTypes.string.isRequired,
            orange200: PropTypes.string.isRequired,
            orange300: PropTypes.string.isRequired,
            orange400: PropTypes.string.isRequired,
            orange500: PropTypes.string.isRequired,
            orange600: PropTypes.string.isRequired,
            orange700: PropTypes.string.isRequired,
            orange800: PropTypes.string.isRequired,
            orange900: PropTypes.string.isRequired,
            // Deep orange
            deepOrange50: PropTypes.string.isRequired,
            deepOrange100: PropTypes.string.isRequired,
            deepOrange200: PropTypes.string.isRequired,
            deepOrange300: PropTypes.string.isRequired,
            deepOrange400: PropTypes.string.isRequired,
            deepOrange500: PropTypes.string.isRequired,
            deepOrange600: PropTypes.string.isRequired,
            deepOrange700: PropTypes.string.isRequired,
            deepOrange800: PropTypes.string.isRequired,
            deepOrange900: PropTypes.string.isRequired,
            // Brown
            brown50: PropTypes.string.isRequired,
            brown100: PropTypes.string.isRequired,
            brown200: PropTypes.string.isRequired,
            brown300: PropTypes.string.isRequired,
            brown400: PropTypes.string.isRequired,
            brown500: PropTypes.string.isRequired,
            brown600: PropTypes.string.isRequired,
            brown700: PropTypes.string.isRequired,
            brown800: PropTypes.string.isRequired,
            brown900: PropTypes.string.isRequired,
            // Gray
            gray50: PropTypes.string.isRequired,
            gray100: PropTypes.string.isRequired,
            gray200: PropTypes.string.isRequired,
            gray300: PropTypes.string.isRequired,
            gray400: PropTypes.string.isRequired,
            gray500: PropTypes.string.isRequired,
            gray600: PropTypes.string.isRequired,
            gray700: PropTypes.string.isRequired,
            gray800: PropTypes.string.isRequired,
            gray900: PropTypes.string.isRequired,
            // Blue gray
            blueGray50: PropTypes.string.isRequired,
            blueGray100: PropTypes.string.isRequired,
            blueGray200: PropTypes.string.isRequired,
            blueGray300: PropTypes.string.isRequired,
            blueGray400: PropTypes.string.isRequired,
            blueGray500: PropTypes.string.isRequired,
            blueGray600: PropTypes.string.isRequired,
            blueGray700: PropTypes.string.isRequired,
            blueGray800: PropTypes.string.isRequired,
            blueGray900: PropTypes.string.isRequired,
            // Baseline
            primary: PropTypes.string.isRequired,
            primaryVariant: PropTypes.string.isRequired,
            secondary: PropTypes.string.isRequired,
            secondaryVariant: PropTypes.string.isRequired,
            background: PropTypes.string.isRequired,
            surface: PropTypes.string.isRequired,
            error: PropTypes.string.isRequired,
            onPrimary: PropTypes.string.isRequired,
            onSecondary: PropTypes.string.isRequired,
            onBackground: PropTypes.string.isRequired,
            onSurface: PropTypes.string.isRequired,
            onError: PropTypes.string.isRequired,
        } as {
                [key in keyof Colors]: Requireable<string>['isRequired'];
            }).isRequired,
        spacings: PropTypes.shape({
            s1: PropTypes.string.isRequired,
            s2: PropTypes.string.isRequired,
            s3: PropTypes.string.isRequired,
            s4: PropTypes.string.isRequired,
            s5: PropTypes.string.isRequired,
            s6: PropTypes.string.isRequired,
            s7: PropTypes.string.isRequired,
            s8: PropTypes.string.isRequired,
            s9: PropTypes.string.isRequired,
            s10: PropTypes.string.isRequired,
            s11: PropTypes.string.isRequired,
            s12: PropTypes.string.isRequired,
            s13: PropTypes.string.isRequired,
            s14: PropTypes.string.isRequired,
            s15: PropTypes.string.isRequired,
            s16: PropTypes.string.isRequired,
            s17: PropTypes.string.isRequired,
            s18: PropTypes.string.isRequired,
            s19: PropTypes.string.isRequired,
            s20: PropTypes.string.isRequired,
            s21: PropTypes.string.isRequired,
            s22: PropTypes.string.isRequired,
            s23: PropTypes.string.isRequired,
            s24: PropTypes.string.isRequired,
            s25: PropTypes.string.isRequired,
            s26: PropTypes.string.isRequired,
            s27: PropTypes.string.isRequired,
            s28: PropTypes.string.isRequired,
            s29: PropTypes.string.isRequired,
            s30: PropTypes.string.isRequired,
            s31: PropTypes.string.isRequired,
            s32: PropTypes.string.isRequired,
            s33: PropTypes.string.isRequired,
            s34: PropTypes.string.isRequired,
            s35: PropTypes.string.isRequired,
        } as {
                [key in keyof Spacings]: Requireable<string>['isRequired'];
            })
            .isRequired,
        iconSizes: PropTypes.shape({
            sm: PropTypes.string.isRequired,
            md: PropTypes.string.isRequired,
            lg: PropTypes.string.isRequired,
            xl: PropTypes.string.isRequired,
        } as {
                [key in keyof IconSizes]: Requireable<string>['isRequired'];
            })
            .isRequired,
        borderRadius: PropTypes.shape({
            sm: PropTypes.string.isRequired,
            md: PropTypes.string.isRequired,
            lg: PropTypes.string.isRequired,
            xl: PropTypes.string.isRequired,
            circle: PropTypes.string.isRequired,
            pill: PropTypes.string.isRequired,
        } as {
                [key in keyof BorderRadius]: Requireable<string>['isRequired'];
            })
            .isRequired,
        borderWidth: PropTypes.shape({
            sm: PropTypes.string.isRequired,
            md: PropTypes.string.isRequired,
            lg: PropTypes.string.isRequired,
        } as {
                [key in keyof BorderWidth]: Requireable<string>['isRequired'];
            })
            .isRequired,
        typeface: PropTypes.shape({
            primary: PropTypes.string,
            secondary: PropTypes.string,
        } as {
                [key in keyof Typeface]: Requireable<string>;
            }).isRequired,
        typography: PropTypes.shape({
            headline: PropTypes.shape({
                one: typePropType,
                two: typePropType,
                three: typePropType,
                four: typePropType,
                five: typePropType,
                six: typePropType,
            }).isRequired,
            subtitle: PropTypes.shape({
                one: typePropType,
                two: typePropType,
            }).isRequired,
            body: PropTypes.shape({
                one: typePropType,
                two: typePropType,
            }).isRequired,
            button: PropTypes.shape({ typePropType }).isRequired,
            caption: PropTypes.shape({ typePropType }).isRequired,
            overline: PropTypes.shape({ typePropType }).isRequired,
        }).isRequired,
        fontWeight: PropTypes.shape({
            normal: PropTypes.string.isRequired,
            thin: PropTypes.string.isRequired,
            bold: PropTypes.string.isRequired,
            extraBold: PropTypes.string.isRequired,
        } as {
                [key in keyof FontWeight]: Requireable<string>['isRequired'];
            })
            .isRequired,
        breakpoints: PropTypes.shape({
            smDown: PropTypes.string.isRequired,
            smUp: PropTypes.string.isRequired,
            smOnly: PropTypes.string.isRequired,
            mdDown: PropTypes.string.isRequired,
            mdUp: PropTypes.string.isRequired,
            mdOnly: PropTypes.string.isRequired,
            lgDown: PropTypes.string.isRequired,
            lgUp: PropTypes.string.isRequired,
            lgOnly: PropTypes.string.isRequired,
            xlDown: PropTypes.string.isRequired,
            xlUp: PropTypes.string.isRequired,
            xlOnly: PropTypes.string.isRequired,
            xxlDown: PropTypes.string.isRequired,
            xxlUp: PropTypes.string.isRequired,
        } as {
                [key in keyof Breakpoints]: Requireable<string>['isRequired'];
            })
            .isRequired,
        mq: PropTypes.shape({
            smDown: PropTypes.string.isRequired,
            smUp: PropTypes.string.isRequired,
            smOnly: PropTypes.string.isRequired,
            mdDown: PropTypes.string.isRequired,
            mdUp: PropTypes.string.isRequired,
            mdOnly: PropTypes.string.isRequired,
            lgDown: PropTypes.string.isRequired,
            lgUp: PropTypes.string.isRequired,
            lgOnly: PropTypes.string.isRequired,
            xlDown: PropTypes.string.isRequired,
            xlUp: PropTypes.string.isRequired,
            xlOnly: PropTypes.string.isRequired,
            xxlDown: PropTypes.string.isRequired
        } as {
                [key in keyof MediaQueries]: Requireable<string>['isRequired'];
            })
            .isRequired,
        grid: PropTypes.shape({
            default: gridPropType,
            sm: gridPropType,
            md: gridPropType,
            lg: gridPropType,
            xl: gridPropType,
            xxl: gridPropType,
        } as {
                [key in keyof Grid]: Validator<unknown>;
            }).isRequired,
        transitions: PropTypes.shape({
            default: PropTypes.string.isRequired,
            slow: PropTypes.string.isRequired,
        } as {
                [key in keyof Transitions]: Requireable<string>['isRequired'];
            })
            .isRequired,
        zIndex: PropTypes.shape({
            default: PropTypes.number.isRequired,
            absolute: PropTypes.number.isRequired,
            input: PropTypes.number.isRequired,
            popover: PropTypes.number.isRequired,
            tooltip: PropTypes.number.isRequired,
            header: PropTypes.number.isRequired,
            backdrop: PropTypes.number.isRequired,
            modal: PropTypes.number.isRequired,
        } as {
                [key in keyof ZIndex]: Requireable<unknown>;
            }).isRequired,
        elevation: PropTypes.shape({
            density0: PropTypes.string.isRequired,
            density1: PropTypes.string.isRequired,
            density2: PropTypes.string.isRequired,
            density3: PropTypes.string.isRequired,
            density4: PropTypes.string.isRequired,
            density5: PropTypes.string.isRequired,
            density6: PropTypes.string.isRequired,
            density7: PropTypes.string.isRequired,
            density8: PropTypes.string.isRequired,
            density9: PropTypes.string.isRequired,
            density10: PropTypes.string.isRequired,
            density11: PropTypes.string.isRequired,
            density12: PropTypes.string.isRequired,
            density13: PropTypes.string.isRequired,
            density14: PropTypes.string.isRequired,
            density15: PropTypes.string.isRequired,
            density16: PropTypes.string.isRequired,
            density17: PropTypes.string.isRequired,
            density18: PropTypes.string.isRequired,
            density19: PropTypes.string.isRequired,
            density20: PropTypes.string.isRequired,
            density21: PropTypes.string.isRequired,
            density22: PropTypes.string.isRequired,
            density23: PropTypes.string.isRequired,
            density24: PropTypes.string.isRequired,
        } as {
                [key in keyof Elevation]: Requireable<unknown>;
            }).isRequired,
        statesLightTheme: PropTypes.shape({
            enabled: PropTypes.string.isRequired,
            hover: PropTypes.string.isRequired,
            focus: PropTypes.string.isRequired,
            selected: PropTypes.string.isRequired,
            activated: PropTypes.string.isRequired,
            pressed: PropTypes.string.isRequired,
            dragged: PropTypes.string.isRequired,
        } as {
                [key in keyof States]: Requireable<unknown>;
            }).isRequired,
        statesPrimary: PropTypes.shape({
            enabled: PropTypes.string.isRequired,
            hover: PropTypes.string.isRequired,
            focus: PropTypes.string.isRequired,
            selected: PropTypes.string.isRequired,
            activated: PropTypes.string.isRequired,
            pressed: PropTypes.string.isRequired,
            dragged: PropTypes.string.isRequired,
        } as {
                [key in keyof States]: Requireable<unknown>;
            }).isRequired,
    } as unknown as { [key in keyof Theme]: Requireable<unknown> });